# Generated by Django 4.1.2 on 2022-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_topic_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.topic'),
        ),
    ]
